version: '2'
services:
  web:
    image: fpfis/httpd-php:7.3-dev
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD}
      - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      ASDA_USER:
      ASDA_PASSWORD:
      GITHUB_API_TOKEN:
      DOCUMENT_ROOT: ${PWD}
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env

  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome:3.141.59
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - 5900:5900
    expose:
      - 4444

volumes:
  mysql:
